version: '3.8'

volumes:
  postgres_data:
      # driver: local
      external: true

services:
  postgres:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4:latest
  keycloak:
      # image: quay.io/keycloak/keycloak:latest
      # image: ternau/tern-keycloak:1.0.1
      image: ternau/keycloak:15.0.2-1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres